#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

BLACKFIRE_USER="blackfire"
BLACKFIRE_GROUP="blackfire"
LOGDIR=/var/log/blackfire

command=/opt/blackfire/blackfire-agent
command_args="--log-file=\"${LOGDIR}/blackfire.log\" --log-level=\"3\""
pidfile=/run/blackfire/agent.pid
start_stop_daemon_args="--background --make-pidfile --pidfile ${pidfile} \
	--user ${BLACKFIRE_USER} --group ${BLACKFIRE_GROUP}"

start_pre() {
	checkpath -d -m 0775 -o ${BLACKFIRE_USER}:${BLACKFIRE_GROUP} $(dirname ${pidfile})
	checkpath -d -m 0770 -o ${BLACKFIRE_USER}:${BLACKFIRE_GROUP} $LOGDIR
}

stop() {
	kill $(cat $pidfile)
	rm $pidfile
	eend $?
}
