#!/sbin/runscript
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="${RC_SVCNAME}"
pidfile="/run/mongo-connector.pid"
MONGO_CONNECTOR_USER="${RC_SVCNAME}"

depend() {
	need mongodb elasticsearch
}

start() {
	ebegin "Starting ${RC_SVCNAME}"

	checkpath -d -o "${MONGO_CONNECTOR_USER}" -m750 "/var/log/${RC_SVCNAME}"

	start-stop-daemon --start \
		--user $MONGO_CONNECTOR_USER \
		--background \
		--make-pidfile \
		--pidfile $pidfile \
		--stdout /var/log/${RC_SVCNAME}/${RC_SVCNAME}.out \
		--stderr /var/log/${RC_SVCNAME}/${RC_SVCNAME}.err \
		--exec $command -- -c /etc/${RC_SVCNAME}/config.json
	
	eend $?
}

stop() {
	ebegin "Stopping ${RC_SVCNAME}"
	
	start-stop-daemon --stop \
		--pidfile $pidfile

	
	eend $?
}
